
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
cds:
  data-source:
    auto-config:
      enabled: false
  remote:
    services:
      '[BusinessPartnerService]':
        destination:
          # name: BusinessPartnerService
          properties:
          url: http://localhost:4004/odata/v4/business-partner
          authentication: NoAuthentication
        type: odata-v4
